### PR TITLE
Add nearest centroid configuration

### PR DESCRIPTION
**Pull request by s1m0000n**
Working on #8

### CODE REVIEW

**Comment by s1m0000n** [comment]
This PR would also require to fix merge conflicts after #24 is merged. After this is merged, we could remove `Metric` from `Model`

**Comment by vsha96** [comment]
It's great that I've redone the tests as well 👍

**Comment by vsha96** [comment]
that's so nice

> This PR would also require to fix merge conflicts after #24 is merged. After this is merged, we could remove `Metric` from `Model`

For now, you don't need to change `Model` at all
It must be as one solid interface for all models, but probably I will remake it completely

**Review by vsha96 — APPROVED** [review]
Great! Thank you @s1m0000n

**Pull request merged**
